package backend;

public class HTMLProviderIndex {
	
	
//	String s="";	
//	static {
//		
//		
//	}
//	
	public static String getIndex() {

		String s=
				"<!doctype html>\r\n"
				+ "<html lang=\"en\">\r\n"
				+ "\r\n"
				+ "<head>\r\n"
				+ "  <meta charset=\"utf-8\">\r\n"
				+ "  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n"
				+ "\r\n"
				+ "  <!--Bootstrap CDN-->\r\n"
				+ "  <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css\" rel=\"stylesheet\"\r\n"
				+ "    integrity=\"sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor\" crossorigin=\"anonymous\">\r\n"
				+ "\r\n"
				+ "  <link rel=\"stylesheet\" href=\"https://unpkg.com/aos@next/dist/aos.css\" />\r\n"
				+ "\r\n"
				+ "  <!--Font-awesome CDN-->\r\n"
				+ "  <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css\">\r\n"
				+ "\r\n"
				+ "  <!--Link CSS-->\r\n"
				+ "  <link rel=\"stylesheet\" href=\"/CSS/fstyle.css\">\r\n"
				+ "  <link rel=\"stylesheet\" href=\"Food Delivery site (Project-1)/CSS/bootstrap.min.css\">\r\n"
				+ "\r\n"
				+ "  <!--Favicon-->\r\n"
				+ "  <link rel=\"icon\" type=\"image/x-icon\" href=\"images\\logosquare.jpeg\">\r\n"
				+ "\r\n"
				+ "  <title>Online Foods</title>\r\n"
				+ "\r\n"
				+ "</head>\r\n"
				+ "\r\n"
				+ "<body>\r\n"
				+ "  \r\n"
				+ "       <!-- ============================================ -->\r\n"
				+ "       <!-- -------- Developed By : Shaikh Minhaj ------ -->\r\n"
				+ "       <!-- ============================================ --> \r\n"
				+ "  \r\n"
				+ "  <!---------------------------------------------Header------------------------------------------------->\r\n"
				+ "  <div class=\"container\">\r\n"
				+ "    <header class=\"d-flex flex-wrap align-items-center justify-content-center justify-content-md-between py-3  \">\r\n"
				+ "      <a href=\"/\" class=\"d-flex align-items-center col-md-3 mb-2 mb-md-0 text-dark text-decoration-none\">\r\n"
				+ "        <img src=\"images\\LOGO.jpeg\" width=\"120\" height=\"40px\">\r\n"
				+ "      </a>\r\n"
				+ "\r\n"
				+ "      <ul class=\"nav col-12 col-md-auto mb-2 justify-content-center mb-md-0\">\r\n"
				+ "        <li><a href=\"#home\" class=\"nav-link px-2 link-secondary\">Home</a></li>\r\n"
				+ "        <li><a href=\"#offerd\" class=\"nav-link px-2 link-dark\">Offer & Deals</a></li>\r\n"
				+ "        <li><a href=\"#custom-cards\" class=\"nav-link px-2 link-dark\">Categories</a></li>\r\n"
				+ "        <li><a href=\"#order\" class=\"nav-link px-2 link-dark\">Order</a></li>\r\n"
				+ "        <li><a href=\"#faq\" class=\"nav-link px-2 link-dark\">FAQs</a></li>\r\n"
				+ "        <li><a href=\"#about\" class=\"nav-link px-2 link-dark\">About</a></li>\r\n"
				+ "      </ul>\r\n"
				+ "\r\n"
				+ "      <div class=\"dropdown text-end\">\r\n"
				+ "        <a href=\"#\" class=\"d-block link-dark text-decoration-none dropdown-toggle\" id=\"dropdownUser1\"\r\n"
				+ "          data-bs-toggle=\"dropdown\" aria-expanded=\"false\">\r\n"
				+ "          <svg xmlns=\"http://www.w3.org/2000/svg\" width=\"30\" height=\"30\" fill=\"currentColor\" class=\"bi bi-person-circle\"\r\n"
				+ "            viewBox=\"0 0 16 16\">\r\n"
				+ "            <path d=\"M11 6a3 3 0 1 1-6 0 3 3 0 0 1 6 0z\" />\r\n"
				+ "            <path fill-rule=\"evenodd\"\r\n"
				+ "              d=\"M0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8zm8-7a7 7 0 0 0-5.468 11.37C3.242 11.226 4.805 10 8 10s4.757 1.225 5.468 2.37A7 7 0 0 0 8 1z\" />\r\n"
				+ "          </svg>\r\n"
				+ "        </a>\r\n"
				+ "        <ul class=\"dropdown-menu text-small\" aria-labelledby=\"dropdownUser1\">\r\n"
				+ "          <li><a class=\"dropdown-item\" href=\"#\">New project...</a></li>\r\n"
				+ "          <li><a class=\"dropdown-item\" href=\"#\">Settings</a></li>\r\n"
				+ "          <li><a class=\"dropdown-item\" href=\"#\">Profile</a></li>\r\n"
				+ "          <li>\r\n"
				+ "            <hr class=\"dropdown-divider\">\r\n"
				+ "          </li>\r\n"
				+ "          <li><a class=\"dropdown-item\" href=\"#\">Sign out</a></li>\r\n"
				+ "        </ul>\r\n"
				+ "      </div>\r\n"
				+ "\r\n"
				+ "      <div class=\"col-md-4 text-end\">\r\n"
				+ "        <a href=\"Log-in.html\"> <button type=\"button\" class=\"btn btn-outline-primary me-2\">Login</button></a>\r\n"
				+ "        <a href=\"sign-up.html\"> <button type=\"button\" class=\"btn btn-outline-success me-4\">Sign-up</button></a>\r\n"
				+ "        <a href=\"checkoutpg.html\"><button type=\"button\" class=\"btn btn-danger\">\r\n"
				+ "            <svg xmlns=\"http://www.w3.org/2000/svg\" width=\"16\" height=\"16\" fill=\"currentColor\" class=\"bi bi-cart3\"\r\n"
				+ "              viewBox=\"0 0 16 16\">\r\n"
				+ "              <path\r\n"
				+ "                d=\"M0 1.5A.5.5 0 0 1 .5 1H2a.5.5 0 0 1 .485.379L2.89 3H14.5a.5.5 0 0 1 .49.598l-1 5a.5.5 0 0 1-.465.401l-9.397.472L4.415 11H13a.5.5 0 0 1 0 1H4a.5.5 0 0 1-.491-.408L2.01 3.607 1.61 2H.5a.5.5 0 0 1-.5-.5zM3.102 4l.84 4.479 9.144-.459L13.89 4H3.102zM5 12a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm7 0a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm-7 1a1 1 0 1 1 0 2 1 1 0 0 1 0-2zm7 0a1 1 0 1 1 0 2 1 1 0 0 1 0-2z\">\r\n"
				+ "              </path>\r\n"
				+ "            </svg>\r\n"
				+ "            Cart\r\n"
				+ "          </button>\r\n"
				+ "        </a>\r\n"
				+ "      </div>\r\n"
				+ "    </header>\r\n"
				+ "  </div>\r\n"
				+ "\r\n"
				+ "  <!----------------------------------Home----------------------------------------->\r\n"
				+ "\r\n"
				+ "  <div class=\"bg-danger\" id=\"home\">\r\n"
				+ "    <div class=\"container content-space-2\">\r\n"
				+ "      <div class=\"row justify-content-lg-between align-items-md-center\">\r\n"
				+ "        <div class=\"col-md-6 mb-5 mb-md-0\">\r\n"
				+ "          <div class=\"mb-3\" data-aos=\"flip-out\">\r\n"
				+ "            <h1 style=\"color: white;\"><b>Order from <i style=\"color: rgb(238, 255, 0);\">\"Online Foods\"</b></i>...</h1>\r\n"
				+ "          </div>\r\n"
				+ "\r\n"
				+ "          <form>\r\n"
				+ "            <!-- Input Card -->\r\n"
				+ "            <div class=\"input-card mb-3\" data-aos=\"fade-in\">\r\n"
				+ "              <div class=\"input-card-form\">\r\n"
				+ "                <label for=\"searchAnswersForm\" class=\"form-label visually-hidden\">Search</label>\r\n"
				+ "                <input type=\"text\" class=\"form-control form-control-lg\" id=\"searchAnswersForm\"\r\n"
				+ "                  placeholder=\"Search your Favorite Food\" aria-label=\"Search for answers\">\r\n"
				+ "\r\n"
				+ "              </div>\r\n"
				+ "            </div>\r\n"
				+ "          </form>\r\n"
				+ "        </div>\r\n"
				+ "        <div class=\"col-md-5\" data-aos=\"fade-out-right\">\r\n"
				+ "\r\n"
				+ "          <div id=\"carouselExampleSlidesOnly\" class=\"carousel slide\" data-bs-ride=\"carousel\">\r\n"
				+ "            <div class=\"carousel-inner\">\r\n"
				+ "              <div class=\"carousel-item active\">\r\n"
				+ "                <img src=\"images\\bg3.jpeg\" class=\"d-block w-100\" alt=\"...\">\r\n"
				+ "              </div>\r\n"
				+ "              <div class=\"carousel-item\">\r\n"
				+ "                <img src=\"images\\bg5.jpeg\" class=\"d-block w-100\" alt=\"...\">\r\n"
				+ "              </div>\r\n"
				+ "              <div class=\"carousel-item\">\r\n"
				+ "                <img src=\"images\\bg2.jpeg\" class=\"d-block w-100\" alt=\"...\">\r\n"
				+ "              </div>\r\n"
				+ "            </div>\r\n"
				+ "          </div>\r\n"
				+ "        </div>\r\n"
				+ "      </div>\r\n"
				+ "    </div>\r\n"
				+ "  </div>\r\n"
				+ "\r\n"
				+ "  <!---------------------------------------Offers and deals----------------------------->\r\n"
				+ "  <div class=\"container-lg my-3\" id=\"offerd\" data-aos=\"flip-down\">\r\n"
				+ "    <div id=\"myCarousel\" class=\"carousel slide\" data-bs-ride=\"carousel\">\r\n"
				+ "      <!-- Carousel indicators -->\r\n"
				+ "      <ol class=\"carousel-indicators\">\r\n"
				+ "        <li data-bs-target=\"#myCarousel\" data-bs-slide-to=\"0\" class=\"active\"></li>\r\n"
				+ "        <li data-bs-target=\"#myCarousel\" data-bs-slide-to=\"1\"></li>\r\n"
				+ "        <li data-bs-target=\"#myCarousel\" data-bs-slide-to=\"2\"></li>\r\n"
				+ "      </ol>\r\n"
				+ "\r\n"
				+ "      <!-- Wrapper for carousel items -->\r\n"
				+ "      <div class=\"carousel-inner\">\r\n"
				+ "        <div class=\"carousel-item active\">\r\n"
				+ "          <a href=\"orders.html\"><img src=\"images/OFFER3.jpeg\" class=\"d-block w-100\" alt=\"Slide 1\"></a>\r\n"
				+ "        </div>\r\n"
				+ "        <div class=\"carousel-item\">\r\n"
				+ "          <a href=\"orders.html\"> <img src=\"images/OFFER2.jpeg\" class=\"d-block w-100\" alt=\"Slide 2\"></a>\r\n"
				+ "        </div>\r\n"
				+ "        <div class=\"carousel-item\">\r\n"
				+ "          <a href=\"orders.html\"> <img src=\"images/OFFER1.jpeg\" class=\"d-block w-100\" alt=\"Slide 3\"></a>\r\n"
				+ "        </div>\r\n"
				+ "      </div>\r\n"
				+ "\r\n"
				+ "      <!-- Carousel controls -->\r\n"
				+ "      <a class=\"carousel-control-prev\" href=\"#myCarousel\" data-bs-slide=\"prev\">\r\n"
				+ "        <span class=\"carousel-control-prev-icon\"></span>\r\n"
				+ "      </a>\r\n"
				+ "      <a class=\"carousel-control-next\" href=\"#myCarousel\" data-bs-slide=\"next\">\r\n"
				+ "        <span class=\"carousel-control-next-icon\"></span>\r\n"
				+ "      </a>\r\n"
				+ "    </div>\r\n"
				+ "  </div>\r\n"
				+ "  <!----------------------------------categories------------------------------------>\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "  <div class=\"container px-4 py-3\" id=\"custom-cards\" data-aos=\"slide-up\">\r\n"
				+ "\r\n"
				+ "    <div class=\"row row-cols-1 row-cols-lg-3 align-items-stretch g-4 py-5\">\r\n"
				+ "      <div class=\"col\">\r\n"
				+ "        <div class=\"card card-cover h-100 overflow-hidden text-white bg-dark rounded-4 shadow-lg\"\r\n"
				+ "          style=\"background-image: url(images/fc1.jpeg );\">\r\n"
				+ "          <div class=\"d-flex flex-column h-100 p-5 pb-3 text-white text-shadow-1\">\r\n"
				+ "            <h2 class=\"pt-5 mt-5 mb-4 display-6 lh-1 fw-bold\">South Indian Dishes</h2>\r\n"
				+ "            <ul class=\"d-flex list-unstyled mt-auto\">\r\n"
				+ "              <li class=\"me-auto\">\r\n"
				+ "                <img src=\"images\\logosquare.jpeg\" alt=\"Bootstrap\" width=\"32\" height=\"32\"\r\n"
				+ "                  class=\"rounded-circle border border-white\">\r\n"
				+ "              </li>\r\n"
				+ "            </ul>\r\n"
				+ "          </div>\r\n"
				+ "        </div>\r\n"
				+ "      </div>\r\n"
				+ "\r\n"
				+ "      <div class=\"col\">\r\n"
				+ "        <div class=\"card card-cover h-100 overflow-hidden text-white bg-dark rounded-4 shadow-lg\"\r\n"
				+ "          style=\"background-image: url(images/fc3.jpeg );\">\r\n"
				+ "          <div class=\"d-flex flex-column h-100 p-5 pb-3 text-white text-shadow-1\">\r\n"
				+ "            <h2 class=\"pt-5 mt-5 mb-4 display-6 lh-1 fw-bold\">Chiken </h2>\r\n"
				+ "            <ul class=\"d-flex list-unstyled mt-auto\">\r\n"
				+ "              <li class=\"me-auto\">\r\n"
				+ "                <img src=\"images\\logosquare.jpeg\" alt=\"Bootstrap\" width=\"32\" height=\"32\"\r\n"
				+ "                  class=\"rounded-circle border border-white\">\r\n"
				+ "              </li>\r\n"
				+ "            </ul>\r\n"
				+ "          </div>\r\n"
				+ "        </div>\r\n"
				+ "      </div>\r\n"
				+ "\r\n"
				+ "      <div class=\"col\">\r\n"
				+ "        <div class=\"card card-cover h-100 overflow-hidden text-white bg-dark rounded-4 shadow-lg\"\r\n"
				+ "          style=\"background-image: url(images/fc4.jpeg);\">\r\n"
				+ "          <div class=\"d-flex flex-column h-100 p-5 pb-3 text-shadow-1\">\r\n"
				+ "            <h2 class=\"pt-5 mt-5 mb-4 display-6 lh-1 fw-bold\"> Fruits</h2>\r\n"
				+ "            <ul class=\"d-flex list-unstyled mt-auto\">\r\n"
				+ "              <li class=\"me-auto\">\r\n"
				+ "                <img src=\"images\\logosquare.jpeg\" alt=\"Bootstrap\" width=\"32\" height=\"32\"\r\n"
				+ "                  class=\"rounded-circle border border-white\">\r\n"
				+ "              </li>\r\n"
				+ "            </ul>\r\n"
				+ "          </div>\r\n"
				+ "        </div>\r\n"
				+ "      </div>\r\n"
				+ "    </div>\r\n"
				+ "  </div>\r\n"
				+ "\r\n"
				+ "  <div class=\"container px-4 py-3\" id=\"custom-cards\" data-aos=\"slide-up\">\r\n"
				+ "\r\n"
				+ "    <div class=\"row row-cols-1 row-cols-lg-3 align-items-stretch g-4 py-5\">\r\n"
				+ "      <div class=\"col\">\r\n"
				+ "        <div class=\"card card-cover h-100 overflow-hidden text-white bg-dark rounded-4 shadow-lg\"\r\n"
				+ "          style=\"background-image: url(images/fc6.jpeg);\">\r\n"
				+ "          <div class=\"d-flex flex-column h-100 p-5 pb-3 text-white text-shadow-1\">\r\n"
				+ "            <h2 class=\"pt-5 mt-5 mb-4 display-6 lh-1 fw-bold\">Cakes</h2>\r\n"
				+ "            <ul class=\"d-flex list-unstyled mt-auto\">\r\n"
				+ "              <li class=\"me-auto\">\r\n"
				+ "                <img src=\"images\\logosquare.jpeg\" alt=\"Bootstrap\" width=\"32\" height=\"32\"\r\n"
				+ "                  class=\"rounded-circle border border-white\">\r\n"
				+ "              </li>\r\n"
				+ "            </ul>\r\n"
				+ "          </div>\r\n"
				+ "        </div>\r\n"
				+ "      </div>\r\n"
				+ "\r\n"
				+ "      <div class=\"col\">\r\n"
				+ "        <div class=\"card card-cover h-100 overflow-hidden text-white bg-dark rounded-4 shadow-lg\"\r\n"
				+ "          style=\"background-image: url(images/fc7.jpeg);\">\r\n"
				+ "          <div class=\"d-flex flex-column h-100 p-5 pb-3 text-white text-shadow-1\">\r\n"
				+ "            <h2 class=\"pt-5 mt-5 mb-4 display-6 lh-1 fw-bold\">Roti & Curry</h2>\r\n"
				+ "            <ul class=\"d-flex list-unstyled mt-auto\">\r\n"
				+ "              <li class=\"me-auto\">\r\n"
				+ "                <img src=\"images\\logosquare.jpeg\" alt=\"Bootstrap\" width=\"32\" height=\"32\"\r\n"
				+ "                  class=\"rounded-circle border border-white\">\r\n"
				+ "              </li>\r\n"
				+ "            </ul>\r\n"
				+ "          </div>\r\n"
				+ "        </div>\r\n"
				+ "      </div>\r\n"
				+ "\r\n"
				+ "      <div class=\"col\">\r\n"
				+ "        <div class=\"card card-cover h-100 overflow-hidden text-white bg-dark rounded-4 shadow-lg\"\r\n"
				+ "          style=\"background-image: url(images/fc8.jpeg);\">\r\n"
				+ "          <div class=\"d-flex flex-column h-100 p-5 pb-3 text-shadow-1\">\r\n"
				+ "            <h2 class=\"pt-5 mt-5 mb-4 display-6 lh-1 fw-bold\">desserts</h2>\r\n"
				+ "            <ul class=\"d-flex list-unstyled mt-auto\">\r\n"
				+ "              <li class=\"me-auto\">\r\n"
				+ "                <img src=\"images\\logosquare.jpeg\" alt=\"Bootstrap\" width=\"32\" height=\"32\"\r\n"
				+ "                  class=\"rounded-circle border border-white\">\r\n"
				+ "              </li>\r\n"
				+ "            </ul>\r\n"
				+ "          </div>\r\n"
				+ "        </div>\r\n"
				+ "      </div>\r\n"
				+ "    </div>\r\n"
				+ "  </div>\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "  <div class=\"container px-4 py-3\" id=\"custom-cards\" data-aos=\"slide-up\">\r\n"
				+ "\r\n"
				+ "    <div class=\"row row-cols-1 row-cols-lg-3 align-items-stretch g-4 py-5\">\r\n"
				+ "      <div class=\"col\">\r\n"
				+ "        <div class=\"card card-cover h-100 overflow-hidden text-white bg-dark rounded-4 shadow-lg\"\r\n"
				+ "          style=\"background-image: url(images/fc9.jpeg);\">\r\n"
				+ "          <div class=\"d-flex flex-column h-100 p-5 pb-3 text-white text-shadow-1\">\r\n"
				+ "            <h2 class=\"pt-5 mt-5 mb-4 display-6 lh-1 fw-bold\">Sandwich</h2>\r\n"
				+ "            <ul class=\"d-flex list-unstyled mt-auto\">\r\n"
				+ "              <li class=\"me-auto\">\r\n"
				+ "                <img src=\"images\\logosquare.jpeg\" alt=\"Bootstrap\" width=\"32\" height=\"32\"\r\n"
				+ "                  class=\"rounded-circle border border-white\">\r\n"
				+ "              </li>\r\n"
				+ "            </ul>\r\n"
				+ "          </div>\r\n"
				+ "        </div>\r\n"
				+ "      </div>\r\n"
				+ "\r\n"
				+ "      <div class=\"col\">\r\n"
				+ "        <div class=\"card card-cover h-100 overflow-hidden text-white bg-dark rounded-4 shadow-lg\"\r\n"
				+ "          style=\"background-image: url(images/fc11.jpeg);\">\r\n"
				+ "          <div class=\"d-flex flex-column h-100 p-5 pb-3 text-white text-shadow-1\">\r\n"
				+ "            <h2 class=\"pt-5 mt-5 mb-4 display-6 lh-1 fw-bold\">Home Styles</h2>\r\n"
				+ "            <ul class=\"d-flex list-unstyled mt-auto\">\r\n"
				+ "              <li class=\"me-auto\">\r\n"
				+ "                <img src=\"images\\logosquare.jpeg\" alt=\"Bootstrap\" width=\"32\" height=\"32\"\r\n"
				+ "                  class=\"rounded-circle border border-white\">\r\n"
				+ "              </li>\r\n"
				+ "            </ul>\r\n"
				+ "          </div>\r\n"
				+ "        </div>\r\n"
				+ "      </div>\r\n"
				+ "\r\n"
				+ "      <div class=\"col\">\r\n"
				+ "        <div class=\"card card-cover h-100 overflow-hidden text-white bg-dark rounded-4 shadow-lg\"\r\n"
				+ "          style=\"background-image: url(images/fc12.jpeg);\">\r\n"
				+ "          <div class=\"d-flex flex-column h-100 p-5 pb-3 text-shadow-1\">\r\n"
				+ "            <h2 class=\"pt-5 mt-5 mb-4 display-6 lh-1 fw-bold\">Ice Creams, desserts</h2>\r\n"
				+ "            <ul class=\"d-flex list-unstyled mt-auto\">\r\n"
				+ "              <li class=\"me-auto\">\r\n"
				+ "                <img src=\"images\\logosquare.jpeg\" alt=\"Bootstrap\" width=\"32\" height=\"32\"\r\n"
				+ "                  class=\"rounded-circle border border-white\">\r\n"
				+ "              </li>\r\n"
				+ "            </ul>\r\n"
				+ "          </div>\r\n"
				+ "        </div>\r\n"
				+ "      </div>\r\n"
				+ "    </div>\r\n"
				+ "  </div>\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "  <div class=\"container px-4 py-3\" id=\"custom-cards\" data-aos=\"slide-up\">\r\n"
				+ "\r\n"
				+ "    <div class=\"row row-cols-1 row-cols-lg-3 align-items-stretch g-4 py-5\">\r\n"
				+ "      <div class=\"col\">\r\n"
				+ "        <div class=\"card card-cover h-100 overflow-hidden text-white bg-dark rounded-4 shadow-lg\"\r\n"
				+ "          style=\"background-image: url(images/fc14.jpeg);\">\r\n"
				+ "          <div class=\"d-flex flex-column h-100 p-5 pb-3 text-white text-shadow-1\">\r\n"
				+ "            <h2 class=\"pt-5 mt-5 mb-4 display-6 lh-1 fw-bold\">Veg Biryani</h2>\r\n"
				+ "            <ul class=\"d-flex list-unstyled mt-auto\">\r\n"
				+ "              <li class=\"me-auto\">\r\n"
				+ "                <img src=\"images\\logosquare.jpeg\" alt=\"Bootstrap\" width=\"32\" height=\"32\"\r\n"
				+ "                  class=\"rounded-circle border border-white\">\r\n"
				+ "              </li>\r\n"
				+ "            </ul>\r\n"
				+ "          </div>\r\n"
				+ "        </div>\r\n"
				+ "      </div>\r\n"
				+ "\r\n"
				+ "      <div class=\"col\">\r\n"
				+ "        <div class=\"card card-cover h-100 overflow-hidden text-white bg-dark rounded-4 shadow-lg\"\r\n"
				+ "          style=\"background-image: url(images/fc15.jpeg);\">\r\n"
				+ "          <div class=\"d-flex flex-column h-100 p-5 pb-3 text-white text-shadow-1\">\r\n"
				+ "            <h2 class=\"pt-5 mt-5 mb-4 display-6 lh-1 fw-bold\">Tandoori Chicken</h2>\r\n"
				+ "            <ul class=\"d-flex list-unstyled mt-auto\">\r\n"
				+ "              <li class=\"me-auto\">\r\n"
				+ "                <img src=\"images\\logosquare.jpeg\" alt=\"Bootstrap\" width=\"32\" height=\"32\"\r\n"
				+ "                  class=\"rounded-circle border border-white\">\r\n"
				+ "              </li>\r\n"
				+ "            </ul>\r\n"
				+ "          </div>\r\n"
				+ "        </div>\r\n"
				+ "      </div>\r\n"
				+ "\r\n"
				+ "      <div class=\"col\">\r\n"
				+ "        <div class=\"card card-cover h-100 overflow-hidden text-white bg-dark rounded-4 shadow-lg\"\r\n"
				+ "          style=\"background-image: url(images/fc13.jpeg);\">\r\n"
				+ "          <div class=\"d-flex flex-column h-100 p-5 pb-3 text-shadow-1\">\r\n"
				+ "            <h2 class=\"pt-5 mt-5 mb-4 display-6 lh-1 fw-bold\">Burgers</h2>\r\n"
				+ "            <ul class=\"d-flex list-unstyled mt-auto\">\r\n"
				+ "              <li class=\"me-auto\">\r\n"
				+ "                <img src=\"images\\logosquare.jpeg\" alt=\"Bootstrap\" width=\"32\" height=\"32\"\r\n"
				+ "                  class=\"rounded-circle border border-white\">\r\n"
				+ "              </li>\r\n"
				+ "            </ul>\r\n"
				+ "          </div>\r\n"
				+ "        </div>\r\n"
				+ "      </div>\r\n"
				+ "    </div>\r\n"
				+ "  </div>\r\n"
				+ "\r\n"
				+ "  <div class=\"container px-4 py-3\" id=\"custom-cards\" data-aos=\"slide-up\">\r\n"
				+ "\r\n"
				+ "    <div class=\"row row-cols-1 row-cols-lg-3 align-items-stretch g-4 py-5\">\r\n"
				+ "      <div class=\"col\">\r\n"
				+ "        <div class=\"card card-cover h-100 overflow-hidden text-white bg-dark rounded-4 shadow-lg\"\r\n"
				+ "          style=\"background-image: url(images/fc16.jpeg);\">\r\n"
				+ "          <div class=\"d-flex flex-column h-100 p-5 pb-3 text-white text-shadow-1\">\r\n"
				+ "            <h2 class=\"pt-5 mt-5 mb-4 display-6 lh-1 fw-bold\">BreakFasts</h2>\r\n"
				+ "            <ul class=\"d-flex list-unstyled mt-auto\">\r\n"
				+ "              <li class=\"me-auto\">\r\n"
				+ "                <img src=\"images\\logosquare.jpeg\" alt=\"Bootstrap\" width=\"32\" height=\"32\"\r\n"
				+ "                  class=\"rounded-circle border border-white\">\r\n"
				+ "              </li>\r\n"
				+ "            </ul>\r\n"
				+ "          </div>\r\n"
				+ "        </div>\r\n"
				+ "      </div>\r\n"
				+ "\r\n"
				+ "      <div class=\"col\">\r\n"
				+ "        <div class=\"card card-cover h-100 overflow-hidden text-white bg-dark rounded-4 shadow-lg\"\r\n"
				+ "          style=\"background-image: url(images/fc17.jpeg);\">\r\n"
				+ "          <div class=\"d-flex flex-column h-100 p-5 pb-3 text-white text-shadow-1\">\r\n"
				+ "            <h2 class=\"pt-5 mt-5 mb-4 display-6 lh-1 fw-bold\">North Indian Foods</h2>\r\n"
				+ "            <ul class=\"d-flex list-unstyled mt-auto\">\r\n"
				+ "              <li class=\"me-auto\">\r\n"
				+ "                <img src=\"images\\logosquare.jpeg\" alt=\"Bootstrap\" width=\"32\" height=\"32\"\r\n"
				+ "                  class=\"rounded-circle border border-white\">\r\n"
				+ "              </li>\r\n"
				+ "            </ul>\r\n"
				+ "          </div>\r\n"
				+ "        </div>\r\n"
				+ "      </div>\r\n"
				+ "\r\n"
				+ "      <div class=\"col\">\r\n"
				+ "        <div class=\"card card-cover h-100 overflow-hidden text-white bg-dark rounded-4 shadow-lg\"\r\n"
				+ "          style=\"background-image: url(images/fc18.jpeg);\">\r\n"
				+ "          <div class=\"d-flex flex-column h-100 p-5 pb-3 text-shadow-1\">\r\n"
				+ "            <h2 class=\"pt-5 mt-5 mb-4 display-6 lh-1 fw-bold\">Noodles</h2>\r\n"
				+ "            <ul class=\"d-flex list-unstyled mt-auto\">\r\n"
				+ "              <li class=\"me-auto\">\r\n"
				+ "                <img src=\"images\\logosquare.jpeg\" alt=\"Bootstrap\" width=\"32\" height=\"32\"\r\n"
				+ "                  class=\"rounded-circle border border-white\">\r\n"
				+ "              </li>\r\n"
				+ "            </ul>\r\n"
				+ "          </div>\r\n"
				+ "        </div>\r\n"
				+ "      </div>\r\n"
				+ "    </div>\r\n"
				+ "  </div>\r\n"
				+ "\r\n"
				+ "  <div class=\"container px-4 py-3\" id=\"custom-cards\" data-aos=\"slide-up\">\r\n"
				+ "\r\n"
				+ "    <div class=\"row row-cols-1 row-cols-lg-3 align-items-stretch g-4 py-5\">\r\n"
				+ "      <div class=\"col\">\r\n"
				+ "        <div class=\"card card-cover h-100 overflow-hidden text-white bg-dark rounded-4 shadow-lg\"\r\n"
				+ "          style=\"background-image: url(images/fc19.jpeg);\">\r\n"
				+ "          <div class=\"d-flex flex-column h-100 p-5 pb-3 text-white text-shadow-1\">\r\n"
				+ "            <h2 class=\"pt-5 mt-5 mb-4 display-6 lh-1 fw-bold\">Pizza</h2>\r\n"
				+ "            <ul class=\"d-flex list-unstyled mt-auto\">\r\n"
				+ "              <li class=\"me-auto\">\r\n"
				+ "                <img src=\"images\\logosquare.jpeg\" alt=\"Bootstrap\" width=\"32\" height=\"32\"\r\n"
				+ "                  class=\"rounded-circle border border-white\">\r\n"
				+ "              </li>\r\n"
				+ "            </ul>\r\n"
				+ "          </div>\r\n"
				+ "        </div>\r\n"
				+ "      </div>\r\n"
				+ "\r\n"
				+ "      <div class=\"col\">\r\n"
				+ "        <div class=\"card card-cover h-100 overflow-hidden text-white bg-dark rounded-4 shadow-lg\"\r\n"
				+ "          style=\"background-image: url(images/fc20.jpeg);\">\r\n"
				+ "          <div class=\"d-flex flex-column h-100 p-5 pb-3 text-white text-shadow-1\">\r\n"
				+ "            <h2 class=\"pt-5 mt-5 mb-4 display-6 lh-1 fw-bold\">Daal , Rice</h2>\r\n"
				+ "            <ul class=\"d-flex list-unstyled mt-auto\">\r\n"
				+ "              <li class=\"me-auto\">\r\n"
				+ "                <img src=\"images\\logosquare.jpeg\" alt=\"Bootstrap\" width=\"32\" height=\"32\"\r\n"
				+ "                  class=\"rounded-circle border border-white\">\r\n"
				+ "              </li>\r\n"
				+ "            </ul>\r\n"
				+ "          </div>\r\n"
				+ "        </div>\r\n"
				+ "      </div>\r\n"
				+ "\r\n"
				+ "      <div class=\"col\">\r\n"
				+ "        <div class=\"card card-cover h-100 overflow-hidden text-white bg-dark rounded-4 shadow-lg\"\r\n"
				+ "          style=\"background-image: url(images/fc21.jpeg);\">\r\n"
				+ "          <div class=\"d-flex flex-column h-100 p-5 pb-3 text-shadow-1\">\r\n"
				+ "            <h2 class=\"pt-5 mt-5 mb-4 display-6 lh-1 fw-bold\">Coffee, Tea, Cold Drinks</h2>\r\n"
				+ "            <ul class=\"d-flex list-unstyled mt-auto\">\r\n"
				+ "              <li class=\"me-auto\">\r\n"
				+ "                <img src=\"images\\logosquare.jpeg\" alt=\"Bootstrap\" width=\"32\" height=\"32\"\r\n"
				+ "                  class=\"rounded-circle border border-white\">\r\n"
				+ "              </li>\r\n"
				+ "            </ul>\r\n"
				+ "          </div>\r\n"
				+ "        </div>\r\n"
				+ "      </div>\r\n"
				+ "    </div>\r\n"
				+ "  </div>\r\n"
				+ "  <!--------------------------------------Order-Now-------------------------------------------->\r\n"
				+ "  <div class=\"container col-xxl-8 px-4 py-5\" id=\"order\">\r\n"
				+ "    <div class=\"row flex-lg-row-reverse align-items-center g-5 py-5\">\r\n"
				+ "      <div class=\"col-10 col-sm-8 col-lg-6\" data-aos=\"fade-out-down\">\r\n"
				+ "        <img src=\"images\\Ordernowbg1.jpeg\" class=\"d-block mx-lg-auto img-fluid\" alt=\"Bootstrap Themes\" width=\"700\"\r\n"
				+ "          height=\"500\" loading=\"lazy\">\r\n"
				+ "      </div>\r\n"
				+ "      <div class=\"col-lg-6\" data-aos=\"fade-out-up\">\r\n"
				+ "        <h1 class=\"display-5 fw-bold lh-1 mb-3\">Order with<b style=\"color:rgb(245, 0, 0) ;\"><i>\"Online\r\n"
				+ "              Foods\"</i></b>Now...</h1>\r\n"
				+ "        <p class=\"lead\">Hey Guys, Get your <i>Online Foods</i> Favorites delivered right to your doorstep with <i>Online\r\n"
				+ "            Foods</i>. we are here to provide you Halal and fresh food.\r\n"
				+ "          We use only the best ingredients to cook delicious meals for you. In our menu you will find a wide variety of\r\n"
				+ "          dishes, deserts and drinks. Why are you waiting, order now.</p>\r\n"
				+ "        <div class=\"d-grid gap-2 d-md-flex justify-content-md-start\">\r\n"
				+ "          <a href=\"orders.html\"> <button type=\"button\" class=\"btn btn-danger btn-lg px-4 me-md-4\">Order Now</button>\r\n"
				+ "          </a>\r\n"
				+ "        </div>\r\n"
				+ "      </div>\r\n"
				+ "    </div>\r\n"
				+ "  </div>\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "  <!-----------------------About Our Services------------------------->\r\n"
				+ "  <!-- Section with icon, title and description -->\r\n"
				+ "\r\n"
				+ "  <section class=\"py-6\" data-aos=\"slide-up\">\r\n"
				+ "    <div class=\"container bg-danger text-white\">\r\n"
				+ "      <div class=\"row justify-content-start\">\r\n"
				+ "        <div class=\"col-md-6\">\r\n"
				+ "          <div class=\"p-3 text-start border-radius-lg\" data-aos=\"slide-up\">\r\n"
				+ "            <div class=\"icon icon-shape icon-md bg-gradient-info text-start\">\r\n"
				+ "\r\n"
				+ "              <svg xmlns=\"http://www.w3.org/2000/svg\" width=\"36\" height=\"36\" fill=\"currentColor\" class=\"bi bi-clock\"\r\n"
				+ "                viewBox=\"0 0 16 16\">\r\n"
				+ "                <path d=\"M8 3.5a.5.5 0 0 0-1 0V9a.5.5 0 0 0 .252.434l3.5 2a.5.5 0 0 0 .496-.868L8 8.71V3.5z\" />\r\n"
				+ "                <path d=\"M8 16A8 8 0 1 0 8 0a8 8 0 0 0 0 16zm7-8A7 7 0 1 1 1 8a7 7 0 0 1 14 0z\" />\r\n"
				+ "              </svg>\r\n"
				+ "\r\n"
				+ "            </div>\r\n"
				+ "            <h5 class=\"mt-3\">Fast Deliver</h5>\r\n"
				+ "            <p class=\"w-75\">Everything you order at Foods Online will be quickly delivered to your door</p>\r\n"
				+ "          </div>\r\n"
				+ "          <div class=\"p-3 text-start border-radius-lg\" data-aos=\"slide-up\">\r\n"
				+ "            <div class=\"icon icon-shape icon-md bg-gradient-info text-start\">\r\n"
				+ "\r\n"
				+ "              <svg xmlns=\"http://www.w3.org/2000/svg\" width=\"36\" height=\"36\" fill=\"currentColor\" class=\"bi bi-egg-fried\"\r\n"
				+ "                viewBox=\"0 0 16 16\">\r\n"
				+ "                <path d=\"M8 11a3 3 0 1 0 0-6 3 3 0 0 0 0 6z\" />\r\n"
				+ "                <path\r\n"
				+ "                  d=\"M13.997 5.17a5 5 0 0 0-8.101-4.09A5 5 0 0 0 1.28 9.342a5 5 0 0 0 8.336 5.109 3.5 3.5 0 0 0 5.201-4.065 3.001 3.001 0 0 0-.822-5.216zm-1-.034a1 1 0 0 0 .668.977 2.001 2.001 0 0 1 .547 3.478 1 1 0 0 0-.341 1.113 2.5 2.5 0 0 1-3.715 2.905 1 1 0 0 0-1.262.152 4 4 0 0 1-6.67-4.087 1 1 0 0 0-.2-1 4 4 0 0 1 3.693-6.61 1 1 0 0 0 .8-.2 4 4 0 0 1 6.48 3.273z\" />\r\n"
				+ "              </svg>\r\n"
				+ "\r\n"
				+ "            </div>\r\n"
				+ "            <h5 class=\"mt-3\">Fresh Food</h5>\r\n"
				+ "            <p class=\"w-75\">We use only the best ingredients to cook the tasty fresh and halaal food for you.</p>\r\n"
				+ "          </div>\r\n"
				+ "        </div>\r\n"
				+ "        <div class=\"col-md-6\">\r\n"
				+ "          <div class=\"p-3 text-start border-radius-lg\" data-aos=\"slide-up\" data-aos-delay=\"300\">\r\n"
				+ "            <div class=\"icon icon-shape icon-md bg-gradient-info text-start\">\r\n"
				+ "\r\n"
				+ "              <svg xmlns=\"http://www.w3.org/2000/svg\" width=\"36\" height=\"36\" fill=\"currentColor\" class=\"bi bi-award\"\r\n"
				+ "                viewBox=\"0 0 16 16\">\r\n"
				+ "                <path\r\n"
				+ "                  d=\"M9.669.864 8 0 6.331.864l-1.858.282-.842 1.68-1.337 1.32L2.6 6l-.306 1.854 1.337 1.32.842 1.68 1.858.282L8 12l1.669-.864 1.858-.282.842-1.68 1.337-1.32L13.4 6l.306-1.854-1.337-1.32-.842-1.68L9.669.864zm1.196 1.193.684 1.365 1.086 1.072L12.387 6l.248 1.506-1.086 1.072-.684 1.365-1.51.229L8 10.874l-1.355-.702-1.51-.229-.684-1.365-1.086-1.072L3.614 6l-.25-1.506 1.087-1.072.684-1.365 1.51-.229L8 1.126l1.356.702 1.509.229z\" />\r\n"
				+ "                <path d=\"M4 11.794V16l4-1 4 1v-4.206l-2.018.306L8 13.126 6.018 12.1 4 11.794z\" />\r\n"
				+ "              </svg>\r\n"
				+ "\r\n"
				+ "            </div>\r\n"
				+ "            <h5 class=\"mt-3\">Experienced Chefs</h5>\r\n"
				+ "            <p class=\"w-75\">Our staff consists of chefs and cooks with years of Experience.</p>\r\n"
				+ "          </div>\r\n"
				+ "          <div class=\"p-3 text-start border-radius-lg\" data-aos=\"slide-up\" data-aos-delay=\"300\">\r\n"
				+ "            <div class=\"icon icon-shape icon-md bg-gradient-info text-start\">\r\n"
				+ "              <svg xmlns=\"http://www.w3.org/2000/svg\" width=\"36\" height=\"36\" fill=\"currentColor\" class=\"bi bi-box2\"\r\n"
				+ "                viewBox=\"0 0 16 16\">\r\n"
				+ "                <path\r\n"
				+ "                  d=\"M2.95.4a1 1 0 0 1 .8-.4h8.5a1 1 0 0 1 .8.4l2.85 3.8a.5.5 0 0 1 .1.3V15a1 1 0 0 1-1 1H1a1 1 0 0 1-1-1V4.5a.5.5 0 0 1 .1-.3L2.95.4ZM7.5 1H3.75L1.5 4h6V1Zm1 0v3h6l-2.25-3H8.5ZM15 5H1v10h14V5Z\" />\r\n"
				+ "              </svg>\r\n"
				+ "            </div>\r\n"
				+ "            <h5 class=\"mt-3\">A Variety of Dishes</h5>\r\n"
				+ "            <p class=\"w-75\">In our menu you will find a wide variety of dishes, desserts, and drinks.</p>\r\n"
				+ "          </div>\r\n"
				+ "        </div>\r\n"
				+ "      </div>\r\n"
				+ "    </div>\r\n"
				+ "  </section>\r\n"
				+ "  <!-- -------- END Features w/ 4 cols w/ white icon on colored background & title & text -------- -->\r\n"
				+ "\r\n"
				+ "  <!-------------------------------About------------------------------------------>\r\n"
				+ "\r\n"
				+ "  <section class=\"py-5\" id=\"about\">\r\n"
				+ "    <div class=\"container-fluid\">\r\n"
				+ "      <div class=\"row\">\r\n"
				+ "        <div class=\"col-lg-5 col-6 mx-lg-0 mx-auto px-lg-5 px-md-0 my-auto\" data-aos=\"fade-in-down\"\r\n"
				+ "          data-aos-delay=\"300\">\r\n"
				+ "          <img class=\"w-100 border-radius-lg shadow\" src=\"images\\aboutusimg.jpeg\">\r\n"
				+ "        </div>\r\n"
				+ "        <div class=\"col-lg-4 col-10 d-flex justify-content-center flex-column mx-auto text-lg-start text-center\"\r\n"
				+ "          data-aos=\"fade-out-down\" data-aos-delay=\"200\">\r\n"
				+ "          <h2 class=\"mb-0 mt-lg-0 mt-4 text-gradient text-danger\">Read more about us</h2>\r\n"
				+ "          <h2 class=\"mb-4\">And find some great partners</h2>\r\n"
				+ "          <p class=\"lead\">It really matters and then like it really doesn’t matter. What matters is the people who are\r\n"
				+ "            sparked by it. And the people who are like offended by it, it doesn’t matter. </p>\r\n"
				+ "          <ul class=\"m-lg-2 m-auto\" data-aos=\"fade-in-down\" data-aos-delay=\"300\">\r\n"
				+ "            <li class=\"lead mb-2\">People are so scared to lose their hope</li>\r\n"
				+ "            <li class=\"lead mb-2\">That’s the main thing people </li>\r\n"
				+ "            <li class=\"lead mb-2\">Thoughts- their perception of themselves!</li>\r\n"
				+ "          </ul>\r\n"
				+ "          <p class=\"blockquote my-3 ps-2\" data-aos=\"fade-in-down\" data-aos-delay=\"300\">\r\n"
				+ "            <span class=\"text-bold\">“Lorem itur at isibusdam, ratione minus doloremque!.”</span>\r\n"
				+ "            <br>\r\n"
				+ "            <small class=\"blockquote-footer\" data-aos=\"fade-in-bottom\" data-aos-delay=\"100\">\r\n"
				+ "              Shaikh Minhaj\r\n"
				+ "            </small>\r\n"
				+ "          </p>\r\n"
				+ "        </div>\r\n"
				+ "      </div>\r\n"
				+ "    </div>\r\n"
				+ "  </section>\r\n"
				+ "\r\n"
				+ "  <!--------------------------------Faq's------------------------------------------>\r\n"
				+ "\r\n"
				+ "  <section class=\"py-4\" id=\"faq\">\r\n"
				+ "    <div class=\"container\" data-aos=\"slide-in\" data-aos-anchor=\".other-element\">\r\n"
				+ "      <div class=\"row my-5\">\r\n"
				+ "        <div class=\"col-md-6 mx-auto text-center\">\r\n"
				+ "          <h2>Frequently Asked Questions</h2>\r\n"
				+ "          <p>A lot of people don&#39;t appreciate the moment until it’s passed. I&#39;m not trying my hardest, and\r\n"
				+ "            I&#39;m not trying to do </p>\r\n"
				+ "        </div>\r\n"
				+ "      </div>\r\n"
				+ "      <div class=\"row\">\r\n"
				+ "        <div class=\"col-md-10 mx-auto\">\r\n"
				+ "          <div class=\"accordion\" id=\"accordionRental\">\r\n"
				+ "            <div class=\"accordion-item mb-3\">\r\n"
				+ "              <h5 class=\"accordion-header\" id=\"headingOne\">\r\n"
				+ "                <button class=\"accordion-button border-bottom font-weight-bold\" type=\"button\" data-bs-toggle=\"collapse\"\r\n"
				+ "                  data-bs-target=\"#collapseOne\" aria-expanded=\"true\" aria-controls=\"collapseOne\">\r\n"
				+ "                  How do I order?\r\n"
				+ "                  <i class=\"collapse-close fa fa-plus text-xs pt-1 position-absolute end-0 me-3\"></i>\r\n"
				+ "                  <i class=\"collapse-open fa fa-minus text-xs pt-1 position-absolute end-0 me-3\"></i>\r\n"
				+ "                </button>\r\n"
				+ "              </h5>\r\n"
				+ "              <div id=\"collapseOne\" class=\"accordion-collapse collapse show\" aria-labelledby=\"headingOne\"\r\n"
				+ "                data-bs-parent=\"#accordionRental\">\r\n"
				+ "                <div class=\"accordion-body text-sm opacity-8\">\r\n"
				+ "                  We’re not always in the position that we want to be at. We’re constantly growing. We’re constantly\r\n"
				+ "                  making mistakes. We’re constantly trying to express ourselves and actualize our dreams. If you have\r\n"
				+ "                  the opportunity to play this game\r\n"
				+ "                  of life you need to appreciate every moment. A lot of people don’t appreciate the moment until it’s\r\n"
				+ "                  passed.\r\n"
				+ "                </div>\r\n"
				+ "              </div>\r\n"
				+ "            </div>\r\n"
				+ "            <div class=\"accordion-item mb-3\">\r\n"
				+ "              <h5 class=\"accordion-header\" id=\"headingTwo\">\r\n"
				+ "                <button class=\"accordion-button border-bottom font-weight-bold\" type=\"button\" data-bs-toggle=\"collapse\"\r\n"
				+ "                  data-bs-target=\"#collapseTwo\" aria-expanded=\"false\" aria-controls=\"collapseTwo\">\r\n"
				+ "                  How can i make the payment?\r\n"
				+ "                  <i class=\"collapse-close fa fa-plus text-xs pt-1 position-absolute end-0 me-3\"></i>\r\n"
				+ "                  <i class=\"collapse-open fa fa-minus text-xs pt-1 position-absolute end-0 me-3\"></i>\r\n"
				+ "                </button>\r\n"
				+ "              </h5>\r\n"
				+ "              <div id=\"collapseTwo\" class=\"accordion-collapse collapse\" aria-labelledby=\"headingTwo\"\r\n"
				+ "                data-bs-parent=\"#accordionRental\">\r\n"
				+ "                <div class=\"accordion-body text-sm opacity-8\">\r\n"
				+ "                  It really matters and then like it really doesn’t matter. What matters is the people who are sparked\r\n"
				+ "                  by it. And the people who are like offended by it, it doesn’t matter. Because it&#39;s about\r\n"
				+ "                  motivating the doers. Because I’m here to follow my dreams and inspire other people to follow their\r\n"
				+ "                  dreams, too.\r\n"
				+ "                  <br>\r\n"
				+ "                  We’re not always in the position that we want to be at. We’re constantly growing. We’re constantly\r\n"
				+ "                  making mistakes. We’re constantly trying to express ourselves and actualize our dreams. If you have\r\n"
				+ "                  the opportunity to play this game of life you need to appreciate every moment. A lot of people don’t\r\n"
				+ "                  appreciate the moment until it’s passed.\r\n"
				+ "                </div>\r\n"
				+ "              </div>\r\n"
				+ "            </div>\r\n"
				+ "            <div class=\"accordion-item mb-3\">\r\n"
				+ "              <h5 class=\"accordion-header\" id=\"headingThree\">\r\n"
				+ "                <button class=\"accordion-button border-bottom font-weight-bold\" type=\"button\" data-bs-toggle=\"collapse\"\r\n"
				+ "                  data-bs-target=\"#collapseThree\" aria-expanded=\"false\" aria-controls=\"collapseThree\">\r\n"
				+ "                  How much time does it take to receive the order?\r\n"
				+ "                  <i class=\"collapse-close fa fa-plus text-xs pt-1 position-absolute end-0 me-3\"></i>\r\n"
				+ "                  <i class=\"collapse-open fa fa-minus text-xs pt-1 position-absolute end-0 me-3\"></i>\r\n"
				+ "                </button>\r\n"
				+ "              </h5>\r\n"
				+ "              <div id=\"collapseThree\" class=\"accordion-collapse collapse\" aria-labelledby=\"headingThree\"\r\n"
				+ "                data-bs-parent=\"#accordionRental\">\r\n"
				+ "                <div class=\"accordion-body text-sm opacity-8\">\r\n"
				+ "                  The time is now for it to be okay to be great. People in this world shun people for being great. For\r\n"
				+ "                  being a bright color. For standing out. But the time is now to be okay to be the greatest you. Would\r\n"
				+ "                  you believe in what you believe in, if you were the only one who believed it?\r\n"
				+ "                  If everything I did failed - which it doesn&#39;t, it actually succeeds - just the fact that I&#39;m\r\n"
				+ "                  willing to fail is an inspiration. People are so scared to lose that they don&#39;t even try. Like,\r\n"
				+ "                  one thing people can&#39;t say is that I&#39;m not trying, and I&#39;m not trying my hardest, and\r\n"
				+ "                  I&#39;m not trying to do the best way I know how.\r\n"
				+ "                </div>\r\n"
				+ "              </div>\r\n"
				+ "            </div>\r\n"
				+ "            <div class=\"accordion-item mb-3\">\r\n"
				+ "              <h5 class=\"accordion-header\" id=\"headingFour\">\r\n"
				+ "                <button class=\"accordion-button border-bottom font-weight-bold\" type=\"button\" data-bs-toggle=\"collapse\"\r\n"
				+ "                  data-bs-target=\"#collapseFour\" aria-expanded=\"false\" aria-controls=\"collapseFour\">\r\n"
				+ "                  Can I resell the products?\r\n"
				+ "                  <i class=\"collapse-close fa fa-plus text-xs pt-1 position-absolute end-0 me-3\"></i>\r\n"
				+ "                  <i class=\"collapse-open fa fa-minus text-xs pt-1 position-absolute end-0 me-3\"></i>\r\n"
				+ "                </button>\r\n"
				+ "              </h5>\r\n"
				+ "              <div id=\"collapseFour\" class=\"accordion-collapse collapse\" aria-labelledby=\"headingFour\"\r\n"
				+ "                data-bs-parent=\"#accordionRental\">\r\n"
				+ "                <div class=\"accordion-body text-sm opacity-8\">\r\n"
				+ "                  I always felt like I could do anything. That’s the main thing people are controlled by! Thoughts-\r\n"
				+ "                  their perception of themselves! They&#39;re slowed down by their perception of themselves. If\r\n"
				+ "                  you&#39;re taught you can’t do anything, you won’t do anything. I was taught I could do everything.\r\n"
				+ "                  <br><br>\r\n"
				+ "                  If everything I did failed - which it doesn&#39;t, it actually succeeds - just the fact that I&#39;m\r\n"
				+ "                  willing to fail is an inspiration. People are so scared to lose that they don&#39;t even try. Like,\r\n"
				+ "                  one thing people can&#39;t say is that I&#39;m not trying, and I&#39;m not trying my hardest, and\r\n"
				+ "                  I&#39;m not trying to do the best way I know how.\r\n"
				+ "                </div>\r\n"
				+ "              </div>\r\n"
				+ "            </div>\r\n"
				+ "            <div class=\"accordion-item mb-3\">\r\n"
				+ "              <h5 class=\"accordion-header\" id=\"headingFifth\">\r\n"
				+ "                <button class=\"accordion-button border-bottom font-weight-bold\" type=\"button\" data-bs-toggle=\"collapse\"\r\n"
				+ "                  data-bs-target=\"#collapseFifth\" aria-expanded=\"false\" aria-controls=\"collapseFifth\">\r\n"
				+ "                  Where do I find the shipping details?\r\n"
				+ "                  <i class=\"collapse-close fa fa-plus text-xs pt-1 position-absolute end-0 me-3\"></i>\r\n"
				+ "                  <i class=\"collapse-open fa fa-minus text-xs pt-1 position-absolute end-0 me-3\"></i>\r\n"
				+ "                </button>\r\n"
				+ "              </h5>\r\n"
				+ "              <div id=\"collapseFifth\" class=\"accordion-collapse collapse\" aria-labelledby=\"headingFifth\"\r\n"
				+ "                data-bs-parent=\"#accordionRental\">\r\n"
				+ "                <div class=\"accordion-body text-sm opacity-8\">\r\n"
				+ "                  There’s nothing I really wanted to do in life that I wasn’t able to get good at. That’s my skill. I’m\r\n"
				+ "                  not really specifically talented at anything except for the ability to learn. That’s what I do. That’s\r\n"
				+ "                  what I’m here for. Don’t be afraid to be wrong because you can’t learn anything from a compliment.\r\n"
				+ "                  I always felt like I could do anything. That’s the main thing people are controlled by! Thoughts-\r\n"
				+ "                  their perception of themselves! They&#39;re slowed down by their perception of themselves. If\r\n"
				+ "                  you&#39;re taught you can’t do anything, you won’t do anything. I was taught I could do everything.\r\n"
				+ "                </div>\r\n"
				+ "              </div>\r\n"
				+ "            </div>\r\n"
				+ "          </div>\r\n"
				+ "        </div>\r\n"
				+ "      </div>\r\n"
				+ "    </div>\r\n"
				+ "  </section>\r\n"
				+ "\r\n"
				+ "  <!--------------------------------Footer------------------------------------------>\r\n"
				+ "\r\n"
				+ " \r\n"
				+ "\r\n"
				+ "  <!--Js-CDN-->\r\n"
				+ "  <script src=\"https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.5/dist/umd/popper.min.js\"\r\n"
				+ "    integrity=\"sha384-Xe+8cL9oJa6tN/veChSP7q+mnSPaj5Bcu9mPX5F5xIGE0DVittaqT5lorf0EI7Vk\"\r\n"
				+ "    crossorigin=\"anonymous\"></script>\r\n"
				+ "  <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.min.js\"\r\n"
				+ "    integrity=\"sha384-kjU+l4N0Yf4ZOJErLsIcvOU2qSb74wXpOhqTvwVx3OElZRweTnQ6d31fXEoRD1Jy\"\r\n"
				+ "    crossorigin=\"anonymous\"></script>\r\n"
				+ "\r\n"
				+ "  <!--AOS-->\r\n"
				+ "  <script src=\"https://unpkg.com/aos@next/dist/aos.js\"></script>\r\n"
				+ "  <script>\r\n"
				+ "    AOS.init();\r\n"
				+ "  </script>\r\n"
				+ "</body>\r\n"
				+ "\r\n"
				+ "</html>\r\n"
				+ "";

return s;
	}
	
			
			

}
